In [1]:
from scipy.spatial import distance

In [2]:
geo_df = pd.read_csv("data/geo_df.csv")

In [3]:
zigbang_df = pd.read_csv("data/zigbang_crawling.csv")

In [4]:
zigbang_df.tail()

,rent,deposit,floor,size,address1,address2,lat,lng,options,manage_cost,parking,elevator,movein_date,agent_name,agent_phone,agent_email,distance
25,50,1000,1층,6.0,서울시 마포구 창전동,6-101,37.551906,126.926734,"에어컨,냉장고,세탁기,인덕션,신발장,싱크대",6만원,불가능,없음,협의가능,홍대부동산프로공인중개사(현선아),010-4228-4463,hsa1973@naver.com,17.793844
26,0,26800,2층,12.0,서울시 마포구 창전동,6-151,37.552535,126.926576,-,없음,가능,있음,2월말,베스트공인중개사(김학찬),010-3432-6961,semplici@nate.com,18.964555
27,40,2000,4층,5.5,서울시 마포구 창전동,6-143,37.553126,126.925964,"에어컨,냉장고,세탁기,인덕션,책상,침대,옷장,신발장,싱크대",5만원,가능,없음,날짜협의,홍대피카소공인중개사(배성희),02-335-7760,kaila386@naver.com,19.156519
28,55,1000,2층,10.0,서울시 마포구 창전동,6-143,37.552605,126.926575,"에어컨,냉장고,세탁기,가스레인지,책상,옷장,신발장,싱크대",5만원,불가능,없음,"즉시입주, 협의가능",홍대부동산뉴스공인중개사(이홍식),02-332-2230,news3218@naver.com,19.358261
29,0,7500,3층,6.0,서울시 마포구 창전동,6-268,37.552150,126.926822,"에어컨,냉장고,세탁기,인덕션,책상,침대,옷장,신발장,싱크대",5만원,불가능,없음,날짜 협의~~~,하늘공인중개사(박보영),02-326-4949,beau0314@hanmail.net,19.366749

In [5]:
location_name = ["초등학교", "중학교", "고등학교", "대학교", "스타벅스", "맥도날드", "역", "몰"]

In [6]:
# df = geo_df[geo_df["label"] == location_name[0]]

In [7]:
def shortest_place(df, lat, lng):
    df_a = df
    df_a["distance"] = ((df_a.lat - lat) ** 2 + (df_a.lng - lng) ** 2) ** (1/2) * 10000
    name = df_a.sort_values("distance").iloc[0]["name"]
    distance = df_a.sort_values("distance").iloc[0]["distance"]
    return name, distance

In [8]:
# name, distance = shortest_place(df, zigbang_df["lat"].iloc[0], zigbang_df["lng"].iloc[0])
# name, distance

In [9]:
ls = []
for i, geo in enumerate(zip(zigbang_df["lat"], zigbang_df["lng"])):
    for loc_name in location_name:
        df = geo_df[geo_df["label"] == loc_name]
        name, distance = shortest_place(df, geo[0], geo[1])
        ls.append(name)
        ls.append(distance)

In [10]:
ls_total = np.array(ls).reshape(30, 16)

In [11]:
columns = ["초등학교","초등학교거리", "중학교", "중학교거리",\
           "고등학교", "고등학교거리", "대학교", "대학교거리",\
           "스타벅스", "스타벅스거리", "맥도날드", "맥도날드거리",\
           "역", "역거리", "몰", "몰거리"]

In [12]:
segun_df = pd.DataFrame(data = ls_total, columns = columns)

In [13]:
total_df = pd.concat([zigbang_df, segun_df], axis=1)

In [14]:
total_df.columns

Index(['rent', 'deposit', 'floor', 'size', 'address1', 'address2', 'lat',
       'lng', 'options', 'manage_cost', 'parking', 'elevator', 'movein_date',
       'agent_name', 'agent_phone', 'agent_email', 'distance', '초등학교',
       '초등학교거리', '중학교', '중학교거리', '고등학교', '고등학교거리', '대학교', '대학교거리', '스타벅스',
       '스타벅스거리', '맥도날드', '맥도날드거리', '역', '역거리', '몰', '몰거리'],
      dtype='object')

In [15]:
a = total_df[["초등학교거리", "중학교거리", "고등학교거리", "대학교거리", "스타벅스거리", "맥도날드거리", "역거리", "몰거리"]].astype('float').sum(axis=1).sort_values()

In [16]:
a.index

Int64Index([22, 27, 15, 12,  7, 13, 28, 26, 10, 23,  9,  8, 20, 14,  3,  2, 21,
             1, 16, 29,  4,  6,  5, 24, 25, 19, 17, 11, 18,  0],
           dtype='int64')

In [19]:
total_df.iloc[a.index].reset_index(drop=True)

,rent,deposit,floor,size,address1,address2,lat,lng,options,manage_cost,...,대학교,대학교거리,스타벅스,스타벅스거리,맥도날드,맥도날드거리,역,역거리,몰,몰거리
0,50,3000,1층,8.0,서울시 마포구 창전동,436-27,37.553197,126.925141,"에어컨,냉장고,세탁기,가스레인지,신발장,싱크대",5만원,...,홍익대학교,47.7385654212632,홍대갤러리,3.2441933707597346,홍익대점,35.2947052174205,홍대입구,40.02650580895476,현대백화점 신촌점,110.38322912341671
1,40,2000,4층,5.5,서울시 마포구 창전동,6-143,37.553126,126.925964,"에어컨,냉장고,세탁기,인덕션,책상,침대,옷장,신발장,싱크대",5만원,...,홍익대학교,47.58459493133523,홍대갤러리,11.469811099434938,홍익대점,42.90479586993408,홍대입구,41.07969248668393,현대백화점 신촌점,102.65880022795079
2,48,500,1층,8.0,서울시 마포구 창전동,436-25,37.553062,126.925297,"에어컨,냉장고,세탁기,인덕션,신발장,싱크대",5만원,...,홍익대학교,46.38515818287902,홍대갤러리,5.1852174134274565,홍익대점,37.32817135012664,홍대입구,41.31169191554125,현대백화점 신촌점,109.23772387074314
3,43,500,2층,5.0,서울시 마포구 창전동,6-142,37.552736,126.925959,"에어컨,냉장고,세탁기,인덕션,옷장,신발장,싱크대",7만원,...,홍익대학교,43.73203571003213,홍대갤러리,12.56220062019616,홍익대점,44.68463600457327,홍대입구,44.93232008937864,현대백화점 신촌점,103.88961074243647
4,33,100,1층,2.5,서울시 마포구 창전동,436-34,37.552902,126.925355,"에어컨,냉장고,세탁기,가스레인지,책상,책장,침대,옷장,신발장,싱크대",없음,...,홍익대학교,44.80391852207217,홍대갤러리,6.49495013863459,홍익대점,38.65612629268072,홍대입구,42.89731849429251,현대백화점 신촌점,109.13612592468559
5,55,1000,3층,8.0,서울시 마포구 창전동,436-5,37.552633,126.926120,"에어컨,냉장고,세탁기,인덕션,옷장,신발장,싱크대",5만원,...,홍익대학교,43.013748153799156,홍대갤러리,14.457656047740548,홍익대점,46.590720497793285,홍대입구,46.18755948548236,현대백화점 신촌점,102.7144429661
6,55,1000,2층,10.0,서울시 마포구 창전동,6-143,37.552605,126.926575,"에어컨,냉장고,세탁기,가스레인지,책상,옷장,신발장,싱크대",5만원,...,홍익대학교,43.912050228649534,홍대갤러리,18.731613586527807,홍익대점,50.70016695642679,홍대입구,47.39676193515049,현대백화점 신촌점,98.53817622628667
7,0,26800,2층,12.0,서울시 마포구 창전동,6-151,37.552535,126.926576,-,없음,...,홍익대학교,43.25145543065077,홍대갤러리,19.00520059729709,홍익대점,51.04058541039882,홍대입구,48.075289410668226,현대백화점 신촌점,98.77557322030033
8,50,500,2층,9.0,서울시 마포구 창전동,6-83,37.552500,126.926124,"에어컨,냉장고,세탁기,가스레인지,신발장,싱크대",4만원,...,홍익대학교,41.72360869084201,홍대갤러리,15.141271784180832,홍익대점,47.3140870676849,홍대입구,47.50767574710979,현대백화점 신촌점,103.12369541076457
9,0,30800,3층,12.0,서울시 마포구 창전동,6-152,37.552497,126.926428,-,1만원,...,홍익대학교,42.44716084574414,홍대갤러리,17.82609760018471,홍익대점,49.94265669672712,홍대입구,48.10664905119526,현대백화점 신촌점,100.28943552097903
10,50,500,2층,9.0,서울시 마포구 창전동,6-83,37.552493,126.926130,"에어컨,냉장고,세탁기,가스레인지,옷장,신발장,싱크대",4만원,...,홍익대학교,41.66829535167766,홍대갤러리,15.223623847137711,홍익대점,47.396686836666206,홍대입구,47.584052733574005,현대백화점 신촌점,103.09617271883769
11,40,1000,1층,7.0,서울시 마포구 창전동,6-84,37.552431,126.926152,"에어컨,냉장고,세탁기,인덕션,전자레인지,옷장,신발장,싱크대",5만원,...,홍익대학교,41.10840712603535,홍대갤러리,15.737038714912138,홍익대점,47.90945797775261,홍대입구,48.23300734717665,현대백화점 신촌점,103.11140522687109
12,75,1000,2층,12.0,서울시 마포구 창전동,6-71,37.552310,126.926520,-,없음,...,홍익대학교,40.93511808303835,홍대갤러리,19.51137646015026,홍익대점,51.6778843066966,홍대입구,50.131973597554115,현대백화점 신촌점,100.12365064580587
13,45,1000,1층,8.0,서울시 마포구 창전동,6-100,37.552289,126.926405,"에어컨,냉장고,세탁기,가스레인지,침대,옷장,신발장,싱크대",5만원,...,홍익대학교,40.385485234981815,홍대갤러리,18.63507613880884,홍익대점,50.808550906284495,홍대입구,50.090831538658705,현대백화점 신촌점,101.26945467343093
14,30,4000,2층,9.0,서울시 마포구 창전동,436-27,37.552712,126.925154,"에어컨,냉장고,세탁기,가스레인지,옷장,신발장",5만원,...,홍익대학교,42.887736104196,홍대갤러리,6.570619934567164,홍익대점,38.084170665631206,홍대입구,44.86084074603154,현대백화점 신촌점,111.61653168304852
15,0,8000,3층,8.0,서울시 마포구 창전동,6-68,37.552336,126.925821,"에어컨,냉장고,세탁기,가스레인지,신발장,싱크대",10만원,...,홍익대학교,39.56148926685717,홍대갤러리,13.718135367395334,홍익대점,45.68997433417214,홍대입구,48.760814016717106,현대백화점 신촌점,106.53552071794755
16,0,20000,4층,14.0,서울시 마포구 창전동,6-79,37.552220,126.926571,"에어컨,가스레인지,신발장",5만원,...,홍익대학교,40.25521827991956,홍대갤러리,20.40850375868894,홍익대점,52.58170270179786,홍대입구,51.119931067643314,현대백화점 신촌점,99.98902752086144
17,52,1000,2층,7.0,서울시 마포구 창전동,436-25,37.552579,126.925276,"에어컨,냉장고,세탁기,인덕션,신발장,싱크대",5만원,...,홍익대학교,41.56010687565198,홍대갤러리,8.330262924271226,홍익대점,39.847435307131384,홍대입구,46.138045754546255,현대백화점 신촌점,110.87034799076868
18,45,1000,반지하,6.6,서울시 마포구 창전동,6-81,37.552149,126.926482,"에어컨,냉장고,세탁기,인덕션,책상,책장,침대,옷장,신발장,싱크대",6만원,...,홍익대학교,39.28682628192579,홍대갤러리,20.054817801655563,홍익대점,52.21619728603799,홍대입구,51.62363200669671,현대백화점 신촌점,101.08429669687727
19,0,7500,3층,6.0,서울시 마포구 창전동,6-268,37.552150,126.926822,"에어컨,냉장고,세탁기,인덕션,책상,침대,옷장,신발장,싱크대",5만원,...,홍익대학교,40.50520707919371,홍대갤러리,22.929550391167965,홍익대점,55.09279069294506,홍대입구,52.44101937725586,현대백화점 신촌점,97.96018725688045
20,38,5000,2층,8.0,서울시 마포구 창전동,6-85,37.552032,126.926277,"에어컨,냉장고,세탁기,인덕션,옷장,신발장,싱크대",6만원,...,홍익대학교,37.55988601044012,홍대갤러리,19.134002123535467,홍익대점,51.161823689050394,홍대입구,52.37268126307627,현대백화점 신촌점,103.43462498933066
21,49,500,4층,6.0,서울시 마포구 창전동,6-85,37.552010,126.926311,"에어컨,냉장고,세탁기,인덕션,전자레인지,책상,침대,옷장,싱크대",7만원,...,홍익대학교,37.45088382764784,홍대갤러리,19.539367304468776,홍익대점,51.57139155967011,홍대입구,52.646374784409,현대백화점 신촌점,103.19887483254992
22,50,500,4층,6.0,서울시 마포구 창전동,6-85,37.551998,126.926298,"에어컨,냉장고,세탁기,인덕션,전자레인지,책상,침대,옷장,신발장,싱크대",6만원,...,홍익대학교,37.29159981738599,홍대갤러리,19.523821276956625,홍익대점,51.53815604477246,홍대입구,52.74869023555374,현대백화점 신촌점,103.36902409038797
23,50,1000,1층,6.0,서울시 마포구 창전동,6-101,37.551931,126.926726,"에어컨,냉장고,세탁기,인덕션,싱크대",6만원,...,홍익대학교,38.11346446835024,홍대갤러리,23.295237324449715,홍익대점,55.442307329257034,홍대입구,54.303290877815655,현대백화점 신촌점,99.73255891546681
24,50,1000,1층,6.0,서울시 마포구 창전동,6-101,37.551906,126.926734,"에어컨,냉장고,세탁기,인덕션,신발장,싱크대",6만원,...,홍익대학교,37.921871572791645,홍대갤러리,23.50790100992003,홍익대점,55.6491162528211,홍대입구,54.56212378812097,현대백화점 신촌점,99.75660488510735
25,40,1000,2층,6.0,서울시 마포구 상수동,86-17,37.550716,126.923525,"에어컨,냉장고,세탁기,가스레인지,싱크대",5만원,...,홍익대학교,28.592284642892587,홍대삼거리,5.673875050387913,홍익대점,44.970794246070426,상수,30.74421347677229,현대백화점 신촌점,133.91479699914092
26,0,25000,4층,30.0,서울시 마포구 창전동,6-181,37.551660,126.926645,-,5만원,...,홍익대학교,35.30963850249048,홍대갤러리,24.353720025868725,홍익대점,56.32080343119943,상수,54.72042579716198,현대백화점 신촌점,101.61266005312677
27,0,20000,4층,15.0,서울시 마포구 창전동,6-79,37.551749,126.926548,"에어컨,전자레인지,신발장,싱크대",10만원,...,홍익대학교,35.755333397233954,홍대갤러리,23.038325485161625,홍익대점,55.013331704244166,상수,54.701407693422034,현대백화점 신촌점,102.11050580238063
28,45,1000,1층,7.0,서울시 마포구 상수동,86-17,37.550747,126.923527,"에어컨,냉장고,세탁기,가스레인지,신발장,싱크대",5만원,...,홍익대학교,28.829602486742136,홍대삼거리,5.935928794868871,홍익대점,44.68287830176444,상수,31.052333017788573,현대백화점 신촌점,133.7711861220975
29,45,1000,3층,6.0,서울시 마포구 서교동,361-4,37.551563,126.924130,"에어컨,냉장고,가스레인지,책상,책장,침대,옷장,신발장,싱크대",5만원,...,홍익대학교,33.28115765783249,홍대공원,9.483792607179064,홍익대점,39.76481931550322,상수,40.541802209778744,현대백화점 신촌점,125.08974332202382

In [30]:
total_df['lat'][22], total_df['lng'][22]

(37.553196556596, 126.92514090902107)

In [31]:
zigbang_df.iloc[22]

rent                                  50
deposit                             3000
floor                                 1층
size                                   8
address1                     서울시 마포구 창전동
address2                          436-27
lat                              37.5532
lng                              126.925
options        에어컨,냉장고,세탁기,가스레인지,신발장,싱크대
manage_cost                          5만원
parking                              불가능
elevator                              없음
movein_date                      즉시입주 가능
agent_name                  천하공인중개사(정용우)
agent_phone                  02-336-2227
agent_email            jyw1003@naver.com
distance                         17.3725
Name: 22, dtype: object